# Generated by Django 5.0.6 on 2024-06-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_alter_actor_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Возраст'),
        ),
    ]
